[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
noBuildCache = true
buildCacheEnabled = false

[service]
buildStrategy = "source"
startCommand = "gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 8 --timeout 0"

[service.ports]
http = "8000"
